### ISSUE TITLE
Task 130 - CRUD Usuario para administración

### ISSUE THREAD

**Issue by Superjaviergf** [fitmeapp-ispp/fitmeapp-frontend#130]
Se debe crear:
- Una vista de listado para mostrar todos los usuarios de la aplicación con un filtro genérico que filtra por todo el texto de la tabla.
- Una vista de detalle del usuario, que también nos valdrá para editar todos sus campos y se podrá usar sin ningún campo para el formulario de creación.
- En la vista genérica, se debe añadir un botón para bloquear usuario, **NO ELIMINARLO**. Para esto será necesario meter en la base de datos un nuevo campo en la tabla usuario que sea "Bloqueado" o algo por el estilo, que si está a True, ese usuario no pueda acceder a la aplicación, pero esa funcionalidad no entra dentro del MVP, pero es como se "eliminarán" los usuarios.
- Los usuarios que ya estén bloqueados deben tener el mismo botón en el listado pero para desbloquearlo (usar otro icono diferente al de bloquear).

**Comment by beallasai** [comment]
Modificada la estimación, requiere más investigación y revisiones de lo previsto.

**Comment by geniusbat** [comment]
A la hora de crear y editar debería haber validación en frontend ya que en caso de que algo falle en back, la info no se añadirá pero en front aparecerá como que sí se ha creado.
