### ISSUE TITLE
Task 131 - CRUD Alimentos para administración

### ISSUE THREAD

**Issue by Superjaviergf** [fitmeapp-ispp/fitmeapp-frontend#131]
Se debe crear:
- Una vista de listado para mostrar todos los alimentos de la aplicación con un filtro genérico que filtra por todo el texto de la tabla.
- Una vista de detalle, que la usaremos también para poder editar todos los campos del registro y para crear uno nuevo, entrando en esta vista con todos los campos vacíos.
- Un botón de eliminar dentro del listado de alimentos, que al pulsarlo se pida un mensaje de confirmación avisando de que esa operación es irreversible, y que al aceptarlo se elimine y se actualice la tabla.

**Comment by beallasai** [comment]
Modificada la estimación, requiere más investigación y revisiones de lo previsto.
