### ISSUE TITLE
Task 171 - Reestructuración del backend de Ejercicios

### ISSUE THREAD

**Issue by angtordom1** [fitmeapp-ispp/fitmeapp-frontend#171]

**Comment by DiegoHill** [comment]
Gustavo y yo (Diego) hemos reestructurado el backend y añadido la colección ejercicio_ejecuciones (que originalmente se iba a llamar ejercicios_recomendados). Hemos comprobado que las modificaciones funcionan consumiendo la API en la vista de ejercicios recomendados.

**Comment by DiegoHill** [comment]
Para mañana queda pendiente la modificación de las vistas para adaptarlas a la nueva estructura de la base de datos. He reestimado la tarea teniendo todo esto en cuenta
