### ISSUE TITLE
Task 331 - Diapositiva del SEO

### ISSUE THREAD

**Issue by Jotaeme55** [fitmeapp-ispp/fitmeapp-frontend#331]

**Comment by Jotaeme55** [comment]
ANUNCIOS: a quiénes se le ponen, en qué mercado nos centramos, dónde nos publicitamos, cómo nos pueden encontrar y palabras clave (SEO).

**Comment by Jotaeme55** [comment]
si tienes dudas de algo preguntame

**Comment by felescgon** [comment]
@Jotaeme55 Revisadas
