### ISSUE TITLE
Task 065 - Creación de manual de usuario de la aplicación

### ISSUE THREAD

**Issue by felescgon** [fitmeapp-ispp/fitmeapp-frontend#65]
Se debe definir un manual de usuario. 
*Hay que hacerlo siguiendo el documento "Softwarte Review Guidelines".*

**Comment by Superjaviergf** [comment]
Es necesario hacer un mockup facilito de la vista donde se seleccionarán los planes de pago

**Comment by Superjaviergf** [comment]
Incluir enlaces una vez esté desplegada la aplicación, ver en el documento mencionado en la descripción de esta tarea.
